using ICSharpCode.AvalonEdit.Document;
using ICSharpCode.AvalonEdit.Highlighting;
using LCLocalizationInterface.LimbusRegistry.JsonTypes;
using static LCLocalizationInterface.LimbusRegistry.InputRichTextFormatter;

namespace LCLocalizationInterface.LimbusRegistry
{
    public class JsonTextEditor : SyntaxedTextEditorBase
    {
        public JsonTextEditor()
        {
            WordWrap = true;

            // Ctrl + Mouse wheel font size adjustment
            PreviewMouseWheel += delegate (object Sender, MouseWheelEventArgs Args)
            {
                if (Keyboard.IsKeyDown(Key.LeftCtrl))
                {
                    Args.Handled = true; // Prevent text scroll
                    this.FontSize += (Args.Delta > 0) ? 1.05 : (this.FontSize >= 5 ? -1.05 : 0);
                }
            };

            // Handler for text pasting to automatically replace \" and \n
            this.AddHandler(DataObject.PastingEvent, new DataObjectPastingEventHandler(delegate (object Sender, DataObjectPastingEventArgs Args)
            {
                string TextToPaste = (string)Args.DataObject.GetData(DataFormats.UnicodeText);

                DataObject TransformedText = new();
                string NewText = TextToPaste.Replace("\\\"", "\"").Replace("\\n", "\n").Cut("\r");

                TransformedText.SetText(NewText, TextDataFormat.Text);

                Args.DataObject = TransformedText;
            }));
        }


        public RichTextFormat LimbusRichTextSyntaxMode { get; set => this.SyntaxHighlighting = @LimbusTextSyntaxesPreset.GeneratedSyntaxes[field = value]; } = RichTextFormat.None;

        public new TextDocument Document
        {
            get => base.Document;
            set
            {
                // ୧((#Φ益Φ#))୨
                if (value.ServiceProvider is TextEditorSyntaxKeyCarrier SyntaxKeyCarrier)
                {
                    if (SyntaxKeyCarrier.CarriedSyntaxKey != this.LimbusRichTextSyntaxMode)
                    {
                        this.LimbusRichTextSyntaxMode = SyntaxKeyCarrier.CarriedSyntaxKey;
                    }
                }
                
                base.Document = value;
            }
        }

        /// <summary>
        /// Discard old and set newly generated by <see cref="@LimbusTextSyntaxesPreset.GenerateSyntaxes"/> using <see cref="RichTextFormat"/> key that currently set <see cref="LimbusTextSyntax"/> has
        /// </summary>
        public void UpdateLimbusTextSyntaxState()
        {
            if (this.SyntaxHighlighting is LimbusTextSyntax OldLimbusTextSyntax)
            {
                this.SyntaxHighlighting = @LimbusTextSyntaxesPreset.GeneratedSyntaxes[OldLimbusTextSyntax.Key];
            }
        }



        public ref struct @LimbusTextSyntaxesPreset
        {
            /// <summary>
            /// Limbus json text syntaxes generated by <see cref="GenerateSyntaxes"/>
            /// </summary>
            public static Dictionary<RichTextFormat, LimbusTextSyntax> GeneratedSyntaxes { get; private set; } = [];

            /// <summary>
            /// Called from <see cref="@PartialStateUpdater.Limbus.LimbusCustomLang.UpdateKeywords"/> after Limbus Company custom lang keywords is loaded (Initially from <see cref="App.OnStartup"/> when <see cref="@Configurazione.Load"/> is called)
            /// <br/><br/>
            /// Creates <see cref="GeneratedSyntaxes"/> Dictionary again with new instances of <see cref="LimbusTextSyntax"/> for each <see cref="RichTextFormat"/> key based on loaded Limbus keywords (See <see cref="LimbusTextSyntax"/>'s constructor for process)
            /// </summary>
            public static void GenerateSyntaxes()
            {
                GeneratedSyntaxes = new()
                {
                    [RichTextFormat.None    ] = new LimbusTextSyntax(SpecifiedRichTextFormat: RichTextFormat.None    ),
                    [RichTextFormat.Skills  ] = new LimbusTextSyntax(SpecifiedRichTextFormat: RichTextFormat.Skills  ),
                    [RichTextFormat.Passives] = new LimbusTextSyntax(SpecifiedRichTextFormat: RichTextFormat.Passives),
                    [RichTextFormat.EGOGifts] = new LimbusTextSyntax(SpecifiedRichTextFormat: RichTextFormat.EGOGifts),
                };

                MainWindowInstance.LimbusJsonTextEditor.UpdateLimbusTextSyntaxState();
                foreach (List<IntenseStareType3> RightMenuTextInputs in @EditorModesShelf.ModesMapping.Select(x => x.AssociatedMode.PresentedRightMenuSytaxedTextInputs))
                {
                    foreach (IntenseStareType3 RightMenuTextInput in RightMenuTextInputs)
                    {
                        RightMenuTextInput.SyntaxHighlighting = GeneratedSyntaxes[RichTextFormat.None];
                    }
                }
            }
        }



        public class LimbusTextSyntax : SyntaxedTextEditorBase.SyntaxHighlightDefinition
        {
            public RichTextFormat Key { get; }

            /// <summary>
            /// New instance of <see cref="LimbusTextSyntax"/> <see cref="IHighlightingDefinition"/> with syntax rules generation according to the given <paramref name="SpecifiedRichTextFormat"/>
            /// </summary>
            public LimbusTextSyntax(RichTextFormat SpecifiedRichTextFormat)
            {
                this.Key = SpecifiedRichTextFormat;

                if (LoadedConfiguration.PreviewSettings.Base.EnableSyntaxHighlight)
                {
                    // Shorthands (Logically comes before everything)
                    // lang=regex
                    if (!string.IsNullOrWhiteSpace(SelectedLimbusCustomLanguage.Keywords_ShorthandsRegex) &&
                        SelectedLimbusCustomLanguage.Keywords_ShorthandsRegex.Contains(@"(?<ID>\w+)")
                    ) {
                        foreach (PlainKeyword Keyword in KeywordsLoader.LoadedKeywords_Bufs.Values)
                        {
                            // lang=regex
                            string ShorthandRegex = SelectedLimbusCustomLanguage.Keywords_ShorthandsRegex.Replace(@"(?<ID>\w+)", Keyword.ID);
                            string Color = ColorDictionaries.LoadedKeywordColors[Keyword.ID!];

                            MainRuleSet.Rules.Add(new HighlightingRule()
                            {
                                Regex = new Regex(ShorthandRegex),
                                Color = new HighlightingColor() { Foreground = new HighlightionBrush(Color) }
                            });
                        }

                        // Brown highlight for all other unknown shorthands
                        MainRuleSet.Rules.Add(new HighlightingRule()
                        {
                            Regex = new Regex(SelectedLimbusCustomLanguage.Keywords_ShorthandsRegex),
                            Color = new HighlightingColor() { Foreground = new HighlightionBrush("#9f6a3a") }
                        });
                    }


                    #region Default tags
                    List<HighlightingSpan> BasicTags_Spans = [
                        new SingleContentRuleSpan(
                            StartAndEndPattern: (Start: new(@"<(sprite name|link)="""), End: new(@""">")),
                            StartAndEndStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.Tags), },
                            ContentPattern: new(@"^\w+$"),
                            ContentStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.TagsValue) }
                        ),
                        new SingleContentRuleSpan(
                            StartAndEndPattern: (Start: new(@"<(font|font-weight)="""), End: new(@""">")),
                            StartAndEndStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.Tags), },
                            ContentPattern: new(@"^.+$"),
                            ContentStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.TagsValue) }
                        ),
                        new SingleContentRuleSpan(
                            StartAndEndPattern: (Start: new(@"<(color|mark color|mark)="), End: new(@">")),
                            StartAndEndStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.Tags), },
                            ContentPattern: new(@"^#([a-fA-F0-9]{8}|[a-fA-F0-9]{6})$"),
                            ContentStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.TagsValue) }
                        ),
                        new SingleContentRuleSpan(
                            StartAndEndPattern: (Start: new(@"<size="), End: new(@"%>")),
                            StartAndEndStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.Tags), },
                            ContentPattern: new(@"^\d+((\.|\,)\d+)?$"),
                            ContentStyle: new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.TagsValue)  }
                        ),
                    ];
                    HighlightingRule BasicTags_Remaining = new()
                    {
                        Regex = new Regex(@"<(b|i|u|s|nobr|sub|sup|noparse)>|</(b|i|u|s|nobr|sub|sup|noparse|link|font|font-weight|size|color|mark)>"),
                        Color = new HighlightingColor() { Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.Tags) }
                    };


                    foreach (HighlightingSpan Span in BasicTags_Spans) MainRuleSet.Spans.Add(Span);
                    MainRuleSet.Rules.Add(BasicTags_Remaining);
                    #endregion



                    if (SpecifiedRichTextFormat.EqualsToOneOf(RichTextFormat.Skills, RichTextFormat.Passives, RichTextFormat.EGOGifts))
                    {
                        // All [KeywordID] and Implicits
                        foreach (PlainKeyword Keyword in KeywordsLoader.LoadedKeywords_Bufs.Values)
                        {
                            string Color = ColorDictionaries.LoadedKeywordColors[Keyword.ID!];

                            MainRuleSet.Rules.Add(new HighlightingRule()
                            {
                                Regex = new Regex(@$"\[{Keyword.ID}\]"),
                                Color = new HighlightingColor() { Foreground = new HighlightionBrush(Color) }
                            });

                            // lang=regex
                            if (SelectedLimbusCustomLanguage.Keywords_AutodetectionRegex.Contains(@"(KeywordNameWillBeHere)"))
                            {
                                MainRuleSet.Rules.Add(new HighlightingRule()
                                {
                                    // lang=regex
                                    Regex = new Regex(SelectedLimbusCustomLanguage.Keywords_AutodetectionRegex.Replace(@"KeywordNameWillBeHere", Regex.Escape(Keyword.Name))),
                                    Color = new HighlightingColor() { Foreground = new HighlightionBrush(Color) }
                                });
                            }
                        }



                        // All [SkillTagID] (But only for Skills and Passives, excluding E.G.O Gifts)
                        if (SpecifiedRichTextFormat.EqualsToOneOf(RichTextFormat.Skills, RichTextFormat.Passives))
                        {
                            foreach (PlainSkillTag SkillTag in KeywordsLoader.LoadedSkillTags.Values)
                            {
                                MainRuleSet.Rules.Add(new HighlightingRule()
                                {
                                    Regex = new Regex(@$"\[{SkillTag.ID}\]"),
                                    Color = SkillTag.ID == "TabExplain"
                                        ? new HighlightingColor() { Underline = true, Foreground = new HighlightionBrush(@Themes.CurrentTheme.JsonEditorSyntax.TabExplainColor) }
                                        : new HighlightingColor() { Foreground = new HighlightionBrush(ColorDictionaries.LoadedSkillTagColors[SkillTag.ID!]) }
                                });
                            }



                            // Green 'Unknown' text for all remaining square brackets without actual IDs
                            if (LoadedConfiguration.Internal.DisableUnknownForUnidentifiedKeywords == false)
                            {
                                MainRuleSet.Rules.Add(new HighlightingRule()
                                {
                                    Regex = new Regex(@"\[(.*?)?\]"),
                                    Color = new HighlightingColor() { Strikethrough = true }
                                });
                            }
                        }


                    
                        // <style> tag
                        MainRuleSet.Spans.Add(new HighlightingSpan()
                        {
                            RuleSet = MainRuleSet, // Copy all highlight rules

                            // lang=regex
                            StartExpression = new Regex(SpecifiedRichTextFormat is RichTextFormat.EGOGifts ? @"<style=""upgradeHighlight"">" : @"<style=""highlight"">"),
                            EndExpression = new Regex(@"</style>"),

                            StartColor = new HighlightingColor() { Foreground = new HighlightionBrush("#f8c200") },
                            EndColor = new HighlightingColor() { Foreground = new HighlightionBrush("#f8c200") },

                            // Highlight inner content in yellow
                            SpanColor = new HighlightingColor()
                            {
                                Foreground = LoadedConfiguration.PreviewSettings.Base.HighlightStyle
                                    ? new HighlightionBrush("#f8c200")
                                    : null
                            }
                        });
                    }
                }
            }
        }
    }
}